### ISSUE TITLE
How to install bandcamp-desktop onto macOS Catalina?

### ISSUE THREAD

**Issue by trileptal** [themagiulio/bandcamp-desktop#25]
Hi!
Sorry for the stupid question but I am new to Github:

How do I install bandcamp-desktop onto macOS? I have tried to make the .AppImage executable but with no success...

**Comment by themagiulio** [comment]
Hi, don't worry no question is stupid!
The latest version of Bandcamp Desktop is distributed as deb, AppImage and exe. The first twos work only on GNU/Linux, instead the exe works on Windows. I decided to don't publish the dmg installer for Mac OS since it has some problems running on Big Sur.
I suggest you to build the application from source following the instructions given in the [README.md](https://github.com/themagiulio/bandcamp-desktop/#readme).
The python script which I have written should do that automatically (see "Build from the master branch" paragraph).

**Comment by trileptal** [comment]
Thanks for your answer!
It did not work at first, till I typed the commands "pip" and "python" as "pip3" and "python3".
But atm it seems to be working as it is downloading. Cheers!

**Comment by themagiulio** [comment]
Perfect! If you have further questions don't hesitate to ask!
